#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set ts=4 sts=4 sw=4 et:
"""
@author: Wu Liang
@authors: 
@date: Jun 4, 2012 8:24:36 PM
@contact: wuliang@maimiaotech.com
@version: 0.0.0
@deprecated:
@license:
@copyright:
"""

from Sku import Sku
from StaffEvalStatById import StaffEvalStatById
from TaohuaSearchItems import TaohuaSearchItems
from PosterPicture import PosterPicture
from TaohuaCateStat import TaohuaCateStat
from Brand import Brand
from ProductImg import ProductImg
from TaohuaOrders import TaohuaOrders
from ArticleSub import ArticleSub
from Task import Task
from TaohuaCateProp import TaohuaCateProp
from Shipping import Shipping
from DiscountDetail import DiscountDetail
from Receiver import Receiver
from ItemCategory import ItemCategory
from Shop import Shop
from CouponDetail import CouponDetail
from TransitStepInfo import TransitStepInfo
from NotifyRefund import NotifyRefund
from Area import Area
from ItemProp import ItemProp
from PurchaseOrder import PurchaseOrder
from UserCredit import UserCredit
from Location import Location
from OnlineTimeById import OnlineTimeById
from PropImg import PropImg
from Picture import Picture
from PosterGoodsInfo import PosterGoodsInfo
from SubPurchaseOrder import SubPurchaseOrder
from ProductPropImg import ProductPropImg
from KfcSearchResult import KfcSearchResult
from GroupMember import GroupMember
from TaohuaCatePropValue import TaohuaCatePropValue
from RefundRemindTimeout import RefundRemindTimeout
from TaohuaItemCommentResult import TaohuaItemCommentResult
from Subscription import Subscription
from PartnerDetail import PartnerDetail
from SellerCat import SellerCat
from GuarantyFund import GuarantyFund
from TaohuaUpdateInfo import TaohuaUpdateInfo
from TaobaokeItemDetail import TaobaokeItemDetail
from Distributor import Distributor
from LogisticsCompany import LogisticsCompany
from AfterSale import AfterSale
from Item import Item
from CollectItem import CollectItem
from ErrorMessage import ErrorMessage
from Trade import Trade
from TaobaokeReport import TaobaokeReport
from OrderAmount import OrderAmount
from ReplyStatById import ReplyStatById
from TaohuaItem import TaohuaItem
from SubscribeMessage import SubscribeMessage
from Member import Member
from NotifyTrade import NotifyTrade
from Msg import Msg
from Evaluation import Evaluation
from ArticleUserSubscribe import ArticleUserSubscribe
from ArticleBizOrder import ArticleBizOrder
from FenxiaoSku import FenxiaoSku
from StaffEvalStatOnDay import StaffEvalStatOnDay
from Discount import Discount
from Subtask import Subtask
from User import User
from ShopCat import ShopCat
from TaobaokeItem import TaobaokeItem
from OnlineTimesOnDay import OnlineTimesOnDay
from TradeRate import TradeRate
from TaohuaItemComment import TaohuaItemComment
from TaohuaCategory import TaohuaCategory
from ReplyStatOnDay import ReplyStatOnDay
from Refund import Refund
from ProductCat import ProductCat
from Coupon import Coupon
from SellerAuthorize import SellerAuthorize
from TaobaokeShop import TaobaokeShop
from Video import Video
from LogisticsPartner import LogisticsPartner
from AuthorizeMessage import AuthorizeMessage
from FenxiaoGrade import FenxiaoGrade
from FenxiaoProduct import FenxiaoProduct
from TradeAmount import TradeAmount
from ItemCat import ItemCat
from ItemImg import ItemImg
from NotifyItem import NotifyItem
from PostageMode import PostageMode
from PictureCategory import PictureCategory
from Product import Product
from TaobaokeReportMember import TaobaokeReportMember
from Poster import Poster
from UserSubscribe import UserSubscribe
from TaohuaOrder import TaohuaOrder
from WaitingTimeById import WaitingTimeById
from PromotionDetail import PromotionDetail
from Postage import Postage
from WaitingTimesOnDay import WaitingTimesOnDay
from NonreplyStatById import NonreplyStatById
from NotifyInfo import NotifyInfo
from PropValue import PropValue
from Activity import Activity
from Chatpeer import Chatpeer
from Order import Order
from ItemSearch import ItemSearch
from NonReplyStatOnDay import NonReplyStatOnDay
from ShopScore import ShopScore
from TradeConfirmFee import TradeConfirmFee
from TaohuaSearchItem import TaohuaSearchItem
from TaohuaItemPVPair import TaohuaItemPVPair
from PosterChannel import PosterChannel
